version: '3.7'

services:

  frontend:
    command:
      - /bin/sh
      - -c
      - |
        CI=true npm test

  api:
    command:
      - /bin/sh
      - -c
      - |
        poetry run pytest -rP -v