version: '3.7'

services:
  frontend:
    container_name: frontend
    build:
      context: ./ui/react-app/
      dockerfile: Dockerfile
    volumes:
      - './ui/react-app:/usr/src/app'
      - '/usr/src/app/node_modules'
    ports:
      - 3000:3000
    stdin_open: true
    environment:
      - CHOKIDAR_USEPOLLING=true
    command:
      - /bin/sh
      - -c
      - |
        ls
        npm start


  api:
    container_name: api
    build:
      context: ./api/flask_api/
      dockerfile: Dockerfile
    ports:
      - 5000:5000
    command:
      - /bin/sh
      - -c
      - |
        ls
        poetry run pytest -rP -v
        poetry run flask --app orders --debug run -h 0.0.0.0
