version: '3.7'

services:
  frontend:
    container_name: frontend
    build:
      context: ./ui/react-app/
      dockerfile: Dockerfile
    volumes:
      - './ui/react-app:/usr/src/app'
      - '/usr/src/app/node_modules'
    ports:
      - 3000:3000
    stdin_open: true
    environment:
      - CHOKIDAR_USEPOLLING=true
    command:
      - /bin/sh
      - -c
      - |
        ls
        npm start


  api:
    container_name: api
    build:
      context: ./api/
      dockerfile: Dockerfile
    volumes:
      - './api:/usr/src/app'
    ports:
      - 8000:8000
    command:
      - /bin/sh
      - -c
      - |
        ls
        poetry run python manage.py runserver 0.0.0.0:8000
