version: '3.7'

services:
  frontend:
    image: ghcr.io/rlratcliffe/deployment-pipeline-challenge:ui-main-8324dbd
    environment:
      - CHOKIDAR_USEPOLLING=true
    command:
      - /bin/sh
      - -c
      - |
        npm start

  api:
    container_name: api
    image: ghcr.io/rlratcliffe/deployment-pipeline-challenge:api-main-8324dbd
    command:
      - /bin/sh
      - -c
      - |
        poetry run flask --app orders --debug run -h 0.0.0.0