version: '3.7'

services:

  frontend:
    container_name: frontend
    build:
      context: ./ui/react-app/
      dockerfile: Dockerfile
    volumes:
      - './ui/react-app:/usr/src/app'
      - '/usr/src/app/node_modules'
    ports:
      - 3000:3000
    stdin_open: true
    environment:
      - CHOKIDAR_USEPOLLING=true
    command: npm start