# Generated by Django 5.0.2 on 2024-02-23 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trace_id', models.CharField(max_length=60)),
                ('abbreviated_name', models.CharField(max_length=60)),
                ('food_ordered', models.CharField(max_length=60)),
                ('started_status', models.BooleanField(default=False)),
                ('processing_status', models.BooleanField(default=False)),
            ],
        ),
    ]
