on:
  push:
    branches: [main]

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: 'Commit (compile, unit test, analysis, build installers in under 5 minutes)'
        run: echo 'This is my commit stage and pipeline will stop if this stage fails'

      - name: 'Artifact/release candidate with a unique id'
        run: echo 'This is where I will publish my package (on github?)'

      - name: 'Acceptance testing in prod-like envrionment'
        run: echo 'This is where the acceptance tests will run'

      - name: 'Production'
        run: echo 'This is where the application will be deployed'